name: Update Competitions

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger of the workflow

permissions:
  contents: write # Grant permission to push changes

jobs:
  update-competitions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Use a specific Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run the update script
        run: node index.js

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes detected.";
            echo "has_changes=false" >> $GITHUB_ENV;
          else
            echo "Changes detected.";
            echo "has_changes=true" >> $GITHUB_ENV;
          fi

      - name: Commit changes
        if: ${{ env.has_changes == 'true' }}
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add competitions.json
          git commit -m "Update competitions.json"
          git push
