name: Check WCA Competitions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update_competitions:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Ensure write access to the repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Check file structure
        run: ls -alh # Print directory contents

      - name: Run the competition check script
        run: |
          echo "Running script..."
          node index.js
        continue-on-error: true

      - name: Show logs for script execution
        run: |
          echo "Showing logs from previous step"
          cat /home/runner/.npm/_logs/*.log

      - name: Commit updated competitions.json
        run: |
          echo "Configuring git user"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          echo "Adding competitions.json"
          git add competitions.json
          echo "Committing changes"
          git commit -m "Update competition data" || echo "No changes to commit"
          echo "Pushing to main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
